### ISSUE TITLE
Multi-line strings should be able to be empty

### ISSUE THREAD

**Issue by hscells** [QUT-IFN660-ECMAScript/Native-ECMAScript#46] opened 2016-04-04 04:51 UTC
It looks like modifying https://github.com/QUT-IFN660-ECMAScript/Native-ECMAScript/blob/develop/grammar.l#L151 to make the newline optional will fix the error people are having with multiline strings.

**Comment by ycfreeman** [comment] 2016-04-06 06:51
seems the issue is fixed after upgrading the compiler? @AnthonyGough

**Comment by AnthonyGough** [comment] 2016-04-06 15:13
We should be able to close this - all Mac users have no issue and Ubuntu users have upgraded compiler so this issue no longer exists - recommend close issue

**Comment by ycfreeman** [comment] 2016-04-07 02:01
closing this

**Closed by ycfreeman** 2016-04-07 02:01 UTC
Labels: bug
